### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by aircyan** [liubiggun/Lua_pppoe#1]
我这边用的是企业闪讯，有心跳验证，现在用Pandora，大概6分钟断线，断线后点击pppoe的“连接”按钮即可重新上网。
所以我想用crontab设定一个计划任务，每5分钟重新连接pppoe，请问这个命令该怎么写呢？谢谢!
*/5 \* \* \* \* root restart pppd 这个试过没用

**Comment by liubiggun** [comment]
重连pppoe命令可以考虑使用：ifup pppoe。其中"pppoe"是相应的网络设备名称(ifconfig 中显示的名称)
话说你这个断线也太频繁了。。。

**Comment by aircyan** [comment]
谢谢回答，不过我已经搞定闪讯了
